name: wiki_valorant
description: "Proyecto de investigacion"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bordered_text: ^2.0.0
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_fortune_wheel: ^1.3.2
  fluttericon: ^2.0.0
  html: ^0.15.5
  http: ^1.2.2
  intl: ^0.20.2
  provider: ^6.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
